//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CADVWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CADV_Patient_ReferralTypes
    {
        public System.Guid ReferralID { get; set; }
        public int ReferralTypeID { get; set; }
    }
}
