//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CADVWeb.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CADVDbEntities : DbContext
    {
        public CADVDbEntities()
            : base("name=CADVDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
            
        public DbSet<CADV_PatientReferral> CADV_PatientReferral { get; set; }        
        public DbSet<CADV_States> CADV_States { get; set; }
        public DbSet<CADV_Doctors> CADV_Doctors { get; set; }
        public DbSet<CADV_UserMaster> CADV_UserMaster { get; set; }
        public DbSet<CADV_UserRoles> CADV_UserRoles { get; set; }
    }
}
